### ISSUE TITLE
Install of ricloud package fails with pip >= v10

### ISSUE THREAD

**Issue by romchambe** [reincubate/ricloud#12]
I have the feeling that with version 10 of pip, the install of the package is not working any more. 

Apparently, the imports from pip should now be done with: 
```Python 
from pip._internal.req import parse_requirements
```
More info in [this post](https://stackoverflow.com/questions/49837301/pip-10-no-module-named-pip-req)

Output of my terminal when trying to install ricloud with pip 10.0.1
```
Collecting ricloud
  Using cached https://files.pythonhosted.org/packages/a9/88/98b5a7378f6a5b6a217d5f297676402549c48981c0336c22542ab1ea0267/ricloud-2.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v9/mprh4w_1495_wv5yckc82d_h0000gn/T/pip-install-Izyh21/ricloud/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
    
    ----------------------------------------

Error:  An error occurred while installing ricloud!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v9/mprh4w_1495_wv5yckc82d_h0000gn/T/pip-install-Izyh21/ricloud/

This is likely caused by a bug in ricloud. Report this to its maintainers.
```

**Comment by hlynursmari1** [comment]
Thanks for making us aware of this! 

We've gone ahead and pushed out v2.3.7 which should resolve the issue. 👍
